# .slather.yml

coverage_service: cobertura_xml
xcodeproj: Example/RxViewModel.xcodeproj
source_directory: Pods/RxViewModel
output_directory: ./
ignore:
  - Example/Tests/**/*
  - Example/Pods/Nimble/**/*
